use godot::prelude::*;

mod clock_impl;
mod rpc_impls;

// Generated by protoc-gen-rosetta-rpc; see ../../generate.py.
include!("generated/mod_tree.rs");

struct ExampleGame;

#[gdextension]
unsafe impl ExtensionLibrary for ExampleGame {}
