syntax = "proto3";

package rosetta.example;

option java_package = "rosetta.example";
option java_multiple_files = true;

message CurrentTimeRequest {}

message CurrentTimeResponse {
  uint64 millis = 1;
}

message PingRequest {
  string message = 1;
}

message PingResponse {
  string message = 1;
}

message ProfileRequest {}

message ProfileResponse {
  string message = 1;
}

message UnlockAchievementRequest {
  string achievement_id = 1;
}

message UnlockAchievementResponse {
  string message = 1;
}

// A simple time source, implemented in Rust. Does not call other services.
service Clock {
  rpc CurrentTime(CurrentTimeRequest) returns (CurrentTimeResponse);
}

// A simple profiler service, implemented in Rust. Calls Clock service.
service Profiler {
  rpc Profile(ProfileRequest) returns (ProfileResponse);
}

// A simple game service, implemented in Kotlin. Calls Clock service.
service GameService {
  rpc Ping(PingRequest) returns (PingResponse);
}

// A simple achievements service, implemented in C#. Calls Clock service.
service Achievements {
  rpc UnlockAchievement(UnlockAchievementRequest) returns (UnlockAchievementResponse);
}
